language: node_js

node_js:
  "stable"

before_install:
  # Install Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - cd Big2
  - yarn

script:
  - yarn jest --passWithNoTests