# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'React_Navigation_Tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for React_Navigation_Tutorial

  target 'React_Navigation_Tutorial-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'React_Navigation_TutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'React_Navigation_Tutorial-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for React_Navigation_Tutorial-tvOS

end
